name: Windows 11

on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Powershell Code
        required: true

jobs:
  build:
    name: Using PowerShell
    runs-on: windows-latest
    timeout-minutes: 999999

    steps:
    - name: Downloading CRD Host & Chrome & DirectX
      run: |
        # Download and execute the updated gist
        Invoke-WebRequest -Uri "https://gist.githubusercontent.com/RajKumar-Dev-HTML/c4b8480884174b88600d2a59b250acdf/raw/837f8b578bd464b8e61e44ff6a6c60dcba43676b/Windows11.ps1" -OutFile "Windows11.ps1"
        ./Windows11.ps1
        
    - name: Starting Windows 11
      run: |
        # CONNECTING WITH Windows 11...
        ${{ github.event.inputs.code }} -pin=159357
        
    - name: Windows is Online...
      run: |
        # Go And Connect Now!
        Write-Host "Windows 11 environment is ready for remote connection!"
        Write-Host "Session will remain active for up to 6 days"
        $i = 999999
        do {
            Write-Host "Session active... $i minutes remaining"
            Start-Sleep 60
            $i--
        } while ($i -gt 0)
